<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>OliverS2EEmbeddedHelper</AssemblyName>
    <RootNamespace>OliverS2EEmbeddedHelper</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json;https://nuget.bepinex.dev/v3/index.json;https://nuget.samboy.dev/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="BootstrapPatches.cs" />
    <Compile Include="ProfileFrame.cs" />
    <Compile Include="UnicodeArabic.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.754" IncludeAssets="compile" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.10" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Il2Cppmscorlib"><HintPath>deps-util/IL2CPP_net6/Il2Cppmscorlib.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem"><HintPath>deps-util/IL2CPP_net6/Il2CppSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>deps-util/IL2CPP_net6/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>deps-util/IL2CPP_net6/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>deps-util/IL2CPP_net6/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
